# Generated by Django 5.0 on 2025-06-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseboat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complementaryservice',
            options={'ordering': ['name'], 'verbose_name': 'Complementary Service', 'verbose_name_plural': 'Complementary Services'},
        ),
        migrations.RemoveField(
            model_name='complementaryservice',
            name='complementary_service',
        ),
        migrations.AddField(
            model_name='complementaryservice',
            name='name',
            field=models.CharField(default='default service', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
