# Generated by Django 5.0 on 2025-06-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseboat', '0002_alter_complementaryservice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementaryservice',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
