# Generated by Django 5.0 on 2025-06-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseboat', '0004_alter_complementaryservice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementaryservice',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
