# Generated by Django 5.0 on 2025-06-20 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseboat', '0005_alter_complementaryservice_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseboat',
            old_name='complementary_service',
            new_name='complementary_services',
        ),
    ]
