# Generated by Django 5.0 on 2025-06-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseboat', '0006_rename_complementary_service_houseboat_complementary_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complementaryservice',
            options={'ordering': ['complementary_service'], 'verbose_name': 'complementary_service', 'verbose_name_plural': 'complementary_services'},
        ),
        migrations.RenameField(
            model_name='complementaryservice',
            old_name='name',
            new_name='complementary_service',
        ),
    ]
