# Generated by Django 5.0 on 2025-06-20 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseboat', '0007_alter_complementaryservice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houseboat',
            options={'ordering': ['houseboat']},
        ),
        migrations.AlterModelOptions(
            name='packages',
            options={'ordering': ['package']},
        ),
        migrations.RenameField(
            model_name='houseboat',
            old_name='name',
            new_name='houseboat',
        ),
        migrations.RenameField(
            model_name='packages',
            old_name='name',
            new_name='package',
        ),
    ]
