# Generated by Django 5.0 on 2025-06-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseboat', '0008_alter_houseboat_options_alter_packages_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementaryservice',
            name='complementary_service',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
