# Generated by Django 5.0 on 2025-06-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseboat', '0014_rename_complementary_services_houseboat_complementary_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houseboat',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='houseboat',
            old_name='houseboat',
            new_name='name',
        ),
    ]
