# Generated by Django 5.0 on 2025-06-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseboat', '0016_alter_complementaryservice_complementary_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseboat',
            old_name='complementary_service',
            new_name='complementary_services',
        ),
    ]
