# Generated by Django 5.0 on 2025-06-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseboat', '0018_houseboat_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.CharField(blank=True, choices=[('luxury', 'Luxury'), ('deluxe', 'Deluxe'), ('premium', 'Premium'), ('standard', 'Standard'), ('budget', 'Budget')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='complementary_services',
            field=models.ManyToManyField(blank=True, to='houseboat.complementaryservice'),
        ),
    ]
