# Generated by Django 5.2.3 on 2025-06-22 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseboat', '0019_booking_category_booking_complementary_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='houseboat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='houseboat.houseboat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='houseboat.service'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='houseboat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='houseboat.houseboat'),
        ),
    ]
