# Generated by Django 5.2.3 on 2025-06-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseboat', '0020_alter_booking_houseboat_alter_booking_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='houseboats',
            new_name='houseboat',
        ),
    ]
