# Generated by Django 5.2.3 on 2025-06-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseboat', '0021_rename_houseboats_service_houseboat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseboat',
            name='amenities',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='houseboat',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='houseboat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='houseboat_images/'),
        ),
        migrations.AlterField(
            model_name='houseboat',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
