# Generated by Django 5.0 on 2025-07-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseboat', '0025_remove_houseboat_complementary_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='complementary_services',
        ),
        migrations.RemoveField(
            model_name='houseboat',
            name='complementary_services',
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
